from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

################################################################
################### PREPROCESSOR PARAMETERS ####################
################################################################

PUNCTUATIONS=[
    ".",  # Period
    ",",  # Comma
    ";",  # Semicolon
    ":",  # Colon
    "!",  # Exclamation Mark
    "?",  # Question Mark
    '"',  # Quotation Marks
    "_",  # Em Dash
    "-",  # Hyphen
    "[",  # Left Bracket
    "]",  # Right Bracket
    "{",  # Left Brace
    "}",  # Right Brace
    "/",  # Slash
    "\\", # Backslash
    "|",  # Vertical Bar
    "@",  # At Symbol
    "#",  # Hash
    "$",  # Dollar Sign
    "%",  # Percent
    "^",  # Caret
    "&",  # Ampersand
    "*",  # Asterisk
    "_",  # Underscore
    "+",  # Plus
    "=",  # Equals
    "<",  # Less Than
    ">",  # Greater Than
    "~",  # Tilde
    "`"   # Grave Accent
]

EN_NUMS = [
    "one", "two", "three", "four", "five",
    "six", "seven", "eight", "nine", "ten",
    "eleven", "twelve", "thirteen", "fourteen", "fifteen",
    "sixteen", "seventeen", "eighteen", "nineteen", "twenty"
]

TOPPINGS= [
'pepperoni',
'sausage',
'ham',
'bacon',
'chicken',
'beef',
'salami',
'anchovies',
'mushrooms',
'onions',
'green peppers',
'black olives',
'green olives',
'pineapple',
'spinach',
'tomatoes',
'jalapenos',
'banana peppers',
'artichoke hearts',
'broccoli',
'corn',
'zucchini',
'eggplant',
'garlic',
'basil',
'arugula',
'sun - dried tomatoes',
'sun dried tomatoes',
'feta cheese',
'goat cheese',
'parmesan',
'mozzarella',
'cheddar',
'provolone',
'ricotta',
'gorgonzola',
'blue cheese',
'asiago',
'romano',
'red onions',
'cilantro',
'barbecue sauce',
'pesto',
'alfredo sauce',
'buffalo sauce',
'ranch dressing',
'hot sauce',
'sriracha',
'honey',
'truffle oil',
'oregano',
'crushed red pepper',
'roasted red peppers',
'portobello mushrooms',
'cherry tomatoes',
'capers',
'rosemary',
'thyme',
'sage',
'lemon zest',
'pickles',
'avocado',
'shredded carrots',
'radicchio',
'kale',
'prosciutto',
'duck',
'lobster',
'shrimp',
'clams',
'crab',
'smoked salmon',
'tuna',
'meatballs',
'pulled pork',
'brisket',
'chorizo',
'pancetta',
'pepperoncini',
'horseradish',
'caramelized onions',
'sweet corn',
'cucumber',
'pears',
'apples',
'figs',
'walnuts',
'almonds',
'pecans',
'pumpkin',
'sweet potatoes',
'beets',
'red bell peppers',
'yellow bell peppers',
'habaneros',
'serranos',
'chipotle peppers',
'okra',
'brussels sprouts',
'parsnips',
'watercress',
'leeks',
'shallots',
'edamame',
'tempeh',
'tofu',
'vegan cheese',
'cashew cheese',
'seitan',
'kimchi',
'sauerkraut',
'nori',
'sesame seeds',
'seaweed',
'wasabi',
'ginger',
'hoisin sauce',
'teriyaki sauce',
'tamarind',
'mango chutney',
'coconut',
'mint',
'dill',
'yogurt',
'fried eggs',
'quail eggs',
'hard - boiled eggs',
'hard boiled eggs',
'caviar',
'gold leaf',
'truffle mushrooms',
'white truffle oil',
'black truffle shavings',
'smoked gouda',
'camembert',
'brie',
'emmental',
'havarti',
'munster',
'gruyere',
'cotija cheese',
'queso fresco',
'paneer',
'chevre',
'fontina',
'asiago fresco',
'wild mushrooms',
'chanterelle mushrooms',
'shiitake mushrooms',
'enoki mushrooms',
'maitake mushrooms',
'black garlic',
'fermented garlic',
'pomegranate seeds',
'cranberries',
'blueberries',
'blackberries',
'strawberries',
'dragon fruit',
'lychee',
'papaya',
'passion fruit',
'guava',
'plantains',
'fried plantains',
'crispy onions',
'fried shallots',
'roasted garlic',
'marinated artichokes',
'balsamic glaze',
'white balsamic',
'red cabbage',
'pickled red onions',
'pickled jalapenos',
'fermented cabbage',
'kimchi sprouts',
'microgreens',
'pea shoots',
'sprouts',
'alfalfa sprouts',
'bean sprouts',
'hemp seeds',
'flax seeds',
'chia seeds',
'sliced almonds',
'hazelnuts',
'pistachios',
'pine nuts',
'marcona almonds',
'tahini drizzle',
'aioli drizzle',
'miso paste',
'roasted sesame oil',
'smoked paprika',
'white pepper',
'cayenne pepper',
'five spice powder',
'chili crisp',
'spicy honey',
'maple syrup',
'agave nectar',
'molasses',
'apple butter',
'pumpkin butter',
'blackberry jam',
'fig jam',
'bacon jam',
'tomato jam',
'onion jam',
'gooseberries',
'elderberries',
'rhubarb',
'carrot ribbons',
'beet greens',
'savoy cabbage',
'bok choy',
'water spinach',
'lotus root',
'lotus seeds',
'roasted chestnuts',
'candied pecans',
'candied walnuts',
'hickory smoked bacon',
'applewood smoked bacon',
'turkey bacon',
'vegan bacon',
'pepper bacon',
'lemon grass',
'coconut cream',
'vegan pesto',
'vegan sausage',
'vegan chorizo'
]

STYLE = [
    'stuffed crust',
    'four season',
    'all cheese',
    'meat lover',
    'all meat',
    'thin crust',
    'deep dish',
    'detroit - style',
    'detroit style',
    'new york - style',
    'new york style',
    'chicago - style',
    'chicago style',
    'sicilian',
    'neapolitan',
    'roman - style',
    'roman style',
    'flatbread',
    'calzone',
    'stromboli',
    'pan',
    'hand - tossed',
    'hand tossed',
    'wood - fired',
    'wood fired',
    'brick oven',
    'grilled',
    'gluten free',
    'gluten - free',
    'vegan',
    'vegetarian',
    'whole wheat crust',
    'multigrain crust',
    'sourdough crust',
    'cheese - stuffed crust',
    'cheese stuffed crust',
    'butter crust',
    'parmesan crust',
    'garlic crust',
    'pretzel crust',
    'cauliflower crust',
    'zucchini crust',
    'broccoli crust',
    'sweet potato crust',
    'crispy crust',
    'cracker crust',
    'chewy crust',
    'honey crust',
    'black sesame crust',
    'spicy crust',
    'charcoal crust',
    'white crust',
    'herb - infused crust',
    'herb infused crust',
    'rosemary crust',
    'thin and crispy',
    'doughy crust',
    'pita bread base',
    'naan bread base',
    'bagel',
    'french bread',
    'taco',
    'dessert',
    'breakfast',
    'stuffed cheesy bites crust',
    'folded crust',
    'brioche base',
    'cornmeal crust',
    'polenta crust',
    'vegan gluten - free crust',
    'vegan gluten free crust',
    'potato crust',
    'rice flour crust',
    'low - carb crust',
    'low carb crust',
    'protein crust',
    'almond flour crust',
    'keto crust',
    'paleo crust',
    'lavash crust',
    'puff pastry base',
    'phyllo dough base',
    'seaweed base',
    'tortilla base',
    'cracker base',
    'matzo base',
    'spelt crust',
    'kamut crust',
    'organic crust',
    'marbled crust',
    'sesame seed crust',
    'poppy seed crust',
    'sweet crust',
    'savory crust',
    'glazed crust',
    'cinnamon sugar crust',
    'cheddar crust',
    'corn crust',
    'rustic crust',
    'artisan crust',
    'beer infused crust',
    'beer - infused crust',
    'malty crust',
    'rye crust',
    'crustless',
    'double crust',
    'triple - layer crust',
    'triple layer crust',
    'honey wheat crust',
    'pineapple - infused crust',
    'pineapple infused crust',
    'carrot crust',
    'spinach crust',
    'beetroot crust',
    'coconut flour crust',
    'everything',
    'nothing',
    "all cheese",
    "meat lovers",
    "vegetarian",
    "vegan",
    "everything",
    "nothing",
    "margarita",
    "supreme",
    "hawaiian",
    "barbecue chicken",
    "buffalo chicken",
    "white",
    "pesto",
    "alfredo",
    "four cheese",
    "five cheese",
    "spicy",
    "mexican",
    "taco",
    "cheeseburger",
    "bacon cheeseburger",
    "seafood",
    "shrimp scampi",
    "smoked salmon",
    "lobster",
    "clam",
    "anchovy",
    "caprese",
    "greek",
    "spinach and feta",
    "artichoke",
    "mushroom",
    "truffle",
    "wild mushroom",
    "pepperoni",
    "double pepperoni",
    "sausage",
    "italian sausage",
    "chicken bacon ranch",
    "bacon and egg",
    "breakfast",
    "brunch",
    "dessert",
    "nutella",
    "fruit",
    "s'mores",
    "cookie",
    "berry",
    "prosciutto",
    "pear and gorgonzola",
    "fig and prosciutto",
    "balsamic and arugula",
    "roasted garlic and herb",
    "spicy salami",
    "diavola",
    "calabrese",
    "hot honey",
    "cheddar and bacon",
    "mac and cheese",
    "potato and rosemary",
    "sweet potato and goat cheese",
    "pumpkin and sage",
    "vegetable medley",
    "ratatouille",
    "thai chicken",
    "korean barbecue",
    "bulgogi",
    "teriyaki chicken",
    "tandoori chicken",
    "butter chicken",
    "paneer tikka",
    "mediterranean",
    "middle eastern",
    "falafel",
    "shawarma",
    "eggplant parmesan",
    "zucchini and squash",
    "cauliflower and cheese",
    "broccoli and cheddar",
    "brussels sprout",
    "caramelized onion",
    "pineapple and ham",
    "chorizo",
    "bbq pulled pork",
    "brisket",
    "smoked meats",
    "cheese and truffle",
    "goat cheese and beet",
    "kale and mushroom",
    "egg",
    "honey mustard chicken",
    "maple bacon",
    "kimchi",
    "kimchi and pork belly",
    "jalapeno popper",
    "chipotle",
    "spinach alfredo",
    "basil pesto chicken",
    "roasted vegetable",
    "corn and ricotta",
    "fried egg and bacon",
    "pulled pork and slaw",
    "black bean and avocado",
    "spaghetti",
    "lasagna",
    "stuffed crust meat lovers",
    "loaded supreme",
    "cheese explosion",
    "garlic lover's"
]

DRINK_TYPES = [
    'water',
    'sparkling water',
    'mineral water',
    'distilled water',
    'tap water',
    'coconut water',
    'milk',
    'almond milk',
    'soy milk',
    'oat milk',
    'rice milk',
    'cow milk',
    'buffalo milk',
    'goat milk',
    'coffee',
    'espresso',
    'americano',
    'latte',
    'cappuccino',
    'macchiato',
    'mocha',
    'flat white',
    'cold brew',
    'nitro cold brew',
    'tea',
    'black tea',
    'green tea',
    'white tea',
    'oolong tea',
    'herbal tea',
    'chamomile tea',
    'peppermint tea',
    'ginger tea',
    'hibiscus tea',
    'matcha',
    'chai',
    'bubble tea',
    'iced tea',
    'soft drink',
    'soda',
    'cola',
    'diet cola',
    'root beer',
    'lemonade',
    'limeade',
    'orange soda',
    'grape soda',
    'ginger ale',
    'tonic water',
    'energy drink',
    'sports drink',
    'smoothie',
    'milkshake',
    'fruit juice',
    'orange juice',
    'apple juice',
    'grape juice',
    'cranberry juice',
    'pineapple juice',
    'mango juice',
    'tomato juice',
    'carrot juice',
    'vegetable juice',
    'kombucha',
    'beer',
    'lager',
    'ale',
    'stout',
    'porter',
    'pilsner',
    'ipa',
    'cider',
    'hard cider',
    'mead',
    'wine',
    'red wine',
    'white wine',
    'rose wine',
    'sparkling wine',
    'champagne',
    'fortified wine',
    'sherry',
    'port',
    'dessert wine',
    'whiskey',
    'scotch',
    'bourbon',
    'rye whiskey',
    'irish whiskey',
    'vodka',
    'gin',
    'rum',
    'white rum',
    'dark rum',
    'spiced rum',
    'tequila',
    'mezcal',
    'brandy',
    'cognac',
    'armagnac',
    'liqueur',
    'amaretto',
    'baileys',
    'triple sec',
    'cointreau',
    'grand marnier',
    'schnapps',
    'absinthe',
    'vermouth',
    'aperitif',
    'digestif',
    'cocktail',
    'martini',
    'margarita',
    'daiquiri',
    'mojito',
    'old fashioned',
    'manhattan',
    'negroni',
    'bloody mary',
    'cosmopolitan',
    'whiskey sour',
    'pina colada',
    'mai tai',
    'long island iced tea',
    'sangria',
    'hot chocolate',
    'chai latte',
    'protein shake',
    'broth',
    'soup',
    'buttermilk',
    'lassi',
    'turmeric latte',
    'sparkling wine',
    'egg nog',
    'punch',
    'shirley temple',
    'mocktail',
    'aloe vera juice',
    'tamarind juice',
    'rose water',
    'barley water',
    'fermented drinks'
]

PIZZA_WORDS = ["pizza",
"pie",
"slice",
"pizzas",
"piza",
"pisa",
"pies",
"pees",
"piis"]

QUANTITIES = [
    'a lot of',
    'extra',
    'many',
    'plenty of',
    'several',
    'a few',
    'heaps of',
    'tons of',
    'loads of',
    'some',
    'a bunch of',
    'additional',
    'double',
    'triple',
    'more',
    'overflowing',
    'piled high',
    'copious',
    'abundant',
    'massive',
    'generous',
    'light',
    'heavy',
    'overflowing',
    'lavish',
    'scant',
    'sparse',
    'ample',
    'excessive',
    'moderate',
    'minimal',
    'countless',
    'myriad',
    'innumerable',
    'surplus',
    'adequate',
    'limited',
    'bountiful',
    'profuse',
    'insufficient',
    'meager',
    'rich',
    'thick',
    'thin',
    'layered',
    'stuffed',
    'a sprinkling of',
    'a handful of',
    'barely any',
    'nearly none',
    'a touch of',
    'just a hint',
    'packed',
    'stacked',
    'teeming',
    'brimming',
    'swimming in',
    'scattered',
    'spread out',
    'garnished with'
]

BLACKLIST    = list(set([ stemmer.stem(x) for x in [] ]))
PIZZA_WORDS = [stemmer.stem(word) for word in PIZZA_WORDS]
################################################################
###################### MODEL PARAMETERS ########################
################################################################

EMBEDDING_SIZE = 100
HIDDEN_SIZE = 128
